"""empty message

Revision ID: 4bcfdfd6a875
Revises:
Create Date: 2023-04-18 16:19:22.725687

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4bcfdfd6a875"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("g_id", sa.VARCHAR(length=255), nullable=True),
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("picture", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", "g_id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
