"""empty message

Revision ID: e48dc1db189b
Revises: 831930d8cdbb
Create Date: 2023-04-19 16:38:22.335257

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e48dc1db189b"
down_revision = "831930d8cdbb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("energy_kcal", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("fat", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("carbohydrates", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("protein", sa.FLOAT(decimal_return_scale=2), nullable=False),
        sa.Column("downvotes", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
